apiVersion: v1
kind: Service
metadata:
  name: kube-dash-api-nodeport
spec:
  type: NodePort
  selector:
    app: kube-dash-api
  ports:
    - protocol: TCP
      port: 8080  # Replace with the port your Rust API is listening on
      targetPort: 8080  # Replace with the port your Rust API is listening on
      nodePort: 30001  # Adjust the nodePort as needed, ensure it's in the range 30000-32767
